# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are configuring is "character"
symbol = "➜"     # The "symbol" segment is being set to "➜"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[battery]
full_symbol = "🔋"
charging_symbol = "⚡️"
discharging_symbol = "💀"

[[battery.display]]
threshold = 10
style = "bold red"

[golang]
symbol = "🏎💨 "

format = """\
  $username\
  $hostname\
  $kubernetes\
  $directory\
  $git_branch\
  $git_state\
  $git_status\
  $package\
  $dotnet\
  $golang\
  $java\
  $nodejs\
  $python\
  $ruby\
  $rust\
  $nix_shell\
  $conda\
  $memory_usage\
  $aws\
  $env_var\
  $cmd_duration\
  $line_break\
  $jobs\
  $battery\
  $time\
  $character\
  """
